CREATE DATABASE kfc;
USE kfc;

CREATE TABLE customers(
id INT UNIQUE NOT NULL AUTO_INCREMENT,
first_name VARCHAR(255) DEFAULT "unknown",
last_name VARCHAR(255) NOT NULL,
phone_no VARCHAR(11) NOT NULL,
over_18 BOOLEAN,
points DECIMAL(6,2),
PRIMARY KEY(id)
);

SHOW TABLES;
DESCRIBE customers;

# HOW TO UPDATE TABLE COLUMN
ALTER TABLE customers ADD age INT NOT NULL;
ALTER TABLE customers DROP COLUMN over_18;
ALTER TABLE customers MODIFY first_name VARCHAR(255) DEFAULT "N/A";