CREATE DATABASE qa;
USE qa;

CREATE TABLE customers(
id INT UNIQUE NOT NULL AUTO_INCREMENT,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
phone_number CHAR(11) NOT NULL,
address VARCHAR(255),
postcode VARCHAR(10),
PRIMARY KEY(id)
);

CREATE TABLE menu(
id INT UNIQUE NOT NULL AUTO_INCREMENT,
item VARCHAR(255) NOT NULL,
price DECIMAL NOT NULL,
available BOOLEAN NOT NULL,
img_url VARCHAR(255),
allergens VARCHAR(255),
PRIMARY KEY(id)
);

CREATE TABLE orders(
id INT UNIQUE AUTO_INCREMENT,
order_date TIMESTAMP,
customer_id INT,
items INT,
total_cost DECIMAL NOT NULL,
order_complete BOOLEAN NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (customer_id) REFERENCES customers(id),
FOREIGN KEY (items) REFERENCES menu(id)
);

